//vendor
export const CREATE_VENDOR_REQUEST = "CREATE_VENDOR_REQUEST"
export const CREATE_VENDOR_SUCCESS = "CREATE_VENDOR_SUCCESS"
export const CREATE_VENDOR_FAIL = "CREATE_VENDOR_FAIL"

export const GET_VENDOR_REQUEST = "GET_VENDOR_REQUEST"
export const GET_VENDOR_SUCCESS = "GET_VENDOR_SUCCESS"
export const GET_VENDOR_FAIL = "GET_VENDOR_FAIL"

export const GET_VENDORS_REQUEST = "GET_VENDORS_REQUEST"
export const GET_VENDORS_SUCCESS = "GET_VENDORS_SUCCESS"
export const GET_VENDORS_FAIL = "GET_VENDORS_FAIL"

export const DELETE_VENDOR_REQUEST = "DELETE_VENDOR_REQUEST"
export const DELETE_VENDOR_SUCCESS = "DELETE_VENDOR_SUCCESS"
export const DELETE_VENDOR_FAIL = "DELETE_VENDOR_FAIL"

//items
export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST"
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS"
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL"

export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST"
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS"
export const GET_ITEM_FAIL = "GET_ITEM_FAIL"

export const SEARCH_ITEMS_REQUEST = "SEARCH_ITEMS_REQUEST"
export const SEARCH_ITEMS_SUCCESS = "SEARCH_ITEMS_SUCCESS"
export const SEARCH_ITEMS_FAIL = "SEARCH_ITEMS_FAIL"

export const CREATE_ITEMS_REQUEST = "CREATE_ITEMS_REQUEST"
export const CREATE_ITEMS_SUCCESS = "CREATE_ITEMS_SUCCESS"
export const CREATE_ITEMS_FAIL = "CREATE_ITEMS_FAIL"

export const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST"
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS"
export const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL"

//categs
export const GET_CATEGS_REQUEST = "GET_CATEGS_REQUEST"
export const GET_CATEGS_SUCCESS = "GET_CATEGS_SUCCESS"
export const GET_CATEGS_FAIL = "GET_CATEGS_FAIL"

//types
export const GET_TYPES_REQUEST = "GET_TYPES_REQUEST"
export const GET_TYPES_SUCCESS = "GET_TYPES_SUCCESS"
export const GET_TYPES_FAIL = "GET_TYPES_FAIL"

//user
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const PROFILE_REQUEST = "PROFILE_REQUEST"
export const GET_PROFILE = "GET_PROFILE"
export const PROFILE_ERROR = "PROFILE_ERROR"
export const PROFILE_RESET = "PROFILE_RESET"

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"

//admin
export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"
export const GET_USERS_RESET = "GET_USERS_RESET"

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_FAIL = "CREATE_USER_FAIL"
export const CREATE_USER_RESET = "CREATE_USER_RESET"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"
export const UPDATE_USER_RESET = "UPDATE_USER_RESET"

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

//purchase
export const CREATE_PURCHASE_REQUEST = "CREATE_PURCHASE_REQUEST"
export const CREATE_PURCHASE_SUCCESS = "CREATE_PURCHASE_SUCCESS"
export const CREATE_PURCHASE_FAIL = "CREATE_PURCHASE_FAIL"
export const CREATE_PURCHASE_RESET = "CREATE_PURCHASE_RESET"

export const GET_PURCHASES_REQUEST = "GET_PURCHASES_REQUEST"
export const GET_PURCHASES_SUCCESS = "GET_PURCHASES_SUCCESS"
export const GET_PURCHASES_FAIL = "GET_PURCHASES_FAIL"
export const GET_PURCHASES_RESET = "GET_PURCHASES_RESET"
